# Generated by Django 6.1.1 on 2026-09-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservoirs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.SlugField(help_text='Identifiant technique (a-z, 0-9, tirets). Utilisé dans le topic MQTT.', unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('niveau', 'Niveau'), ('debit', 'Débit')], max_length=20, verbose_name='Type')),
                ('unite', models.CharField(blank=True, max_length=20, verbose_name='Unité')),
                ('topic_mqtt', models.CharField(blank=True, help_text='Généré automatiquement si vide.', max_length=200, unique=True, verbose_name='Topic MQTT')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text='Dernière IP connue du client MQTT (renseignée par le broker).', null=True, verbose_name='Dernière adresse IP')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Version du firmware')),
                ('certificat_fingerprint', models.CharField(blank=True, help_text="SHA-256 du certificat client utilisé pour l'authentification mutuelle.", max_length=128, verbose_name='Empreinte du certificat TLS')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Champs libres (modèle matériel, emplacement physique, etc.).', verbose_name='Métadonnées')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'Maintenance'), ('desactive', 'Désactivé'), ('inconnu', 'Inconnu')], default='actif', max_length=20, verbose_name='Statut')),
                ('en_ligne', models.BooleanField(default=False, help_text='Raccourci booléen synchronisé avec etat_connexion.', verbose_name='En ligne')),
                ('etat_connexion', models.CharField(choices=[('jamais_connecte', 'Jamais connecté'), ('en_ligne', 'En ligne'), ('hors_ligne', 'Hors ligne'), ('en_erreur', 'En erreur')], default='jamais_connecte', max_length=20, verbose_name='État de connexion')),
                ('derniere_authentification', models.DateTimeField(blank=True, help_text='Dernière authentification TLS réussie auprès du broker.', null=True, verbose_name='Dernière authentification')),
                ('derniere_connexion', models.DateTimeField(blank=True, help_text='Dernière connexion MQTT établie (peut être antérieure à la dernière mesure).', null=True, verbose_name='Dernière connexion')),
                ('derniere_mesure', models.DateTimeField(blank=True, help_text='Date de réception de la dernière mesure (horodatage serveur).', null=True, verbose_name='Dernière mesure')),
                ('derniere_erreur', models.TextField(blank=True, help_text="Dernier message d'erreur remonté par le client MQTT.", verbose_name='Dernière erreur')),
                ('nombre_mesures', models.PositiveBigIntegerField(default=0, verbose_name='Nombre total de mesures')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capteurs', to='reservoirs.reservoir', verbose_name='Réservoir')),
            ],
            options={
                'verbose_name': 'Capteur',
                'verbose_name_plural': 'Capteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(verbose_name='Valeur')),
                ('unite', models.CharField(max_length=20, verbose_name='Unité')),
                ('volume_litres', models.FloatField(blank=True, null=True, verbose_name='Volume (L)')),
                ('pourcentage_remplissage', models.FloatField(blank=True, null=True, verbose_name='Remplissage (%)')),
                ('etat_niveau', models.CharField(blank=True, choices=[('critique', 'Critique'), ('bas', 'Bas'), ('normal', 'Normal'), ('haut', 'Haut'), ('debordement', 'Débordement')], max_length=20, null=True, verbose_name='État du niveau')),
                ('horodatage', models.DateTimeField(verbose_name='Horodatage')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception serveur')),
                ('payload_brut', models.JSONField(blank=True, null=True, verbose_name='Payload brut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='capteurs.capteur', verbose_name='Capteur')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['type'], name='capteurs_ca_type_b5ca53_idx'),
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['statut'], name='capteurs_ca_statut_8eb28f_idx'),
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['etat_connexion'], name='capteurs_ca_etat_co_090c98_idx'),
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['reservoir', 'type'], name='capteurs_ca_reservo_8bb8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='mesure',
            index=models.Index(fields=['capteur', '-horodatage'], name='capteurs_me_capteur_930af3_idx'),
        ),
        migrations.AddIndex(
            model_name='mesure',
            index=models.Index(fields=['etat_niveau'], name='capteurs_me_etat_ni_b9c2ea_idx'),
        ),
    ]
