# Generated by Django 6.1.1 on 2026-09-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type_evenement', models.CharField(choices=[('connexion_valide', 'Connexion avec certificat valide'), ('sans_certificat', 'Connexion sans certificat'), ('faux_certificat', 'Faux certificat'), ('mauvais_mot_de_passe', 'Mauvais mot de passe'), ('sans_tls', 'Connexion sans TLS')], max_length=30)),
                ('resultat', models.CharField(choices=[('accepte', 'Accepté'), ('refuse', 'Refusé')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Événement de sécurité',
                'verbose_name_plural': 'Événements de sécurité',
                'ordering': ['-timestamp'],
            },
        ),
    ]
