# Generated by Django 6.1.1 on 2026-09-15 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capteurs', '0001_initial'),
        ('reservoirs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('niveau_critique_bas', 'Niveau critique bas'), ('niveau_bas', 'Niveau bas'), ('niveau_haut', 'Niveau haut'), ('debordement', 'Débordement'), ('capteur_hors_ligne', 'Capteur hors ligne'), ('capteur_silencieux', 'Capteur silencieux'), ('erreur_capteur', 'Erreur capteur'), ('manuelle', 'Alerte manuelle')], max_length=30, verbose_name='Type')),
                ('gravite', models.CharField(choices=[('info', 'Information'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='avertissement', max_length=20, verbose_name='Gravité')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('acquittee', 'Acquittée'), ('resolue', 'Résolue')], default='active', max_length=20, verbose_name='Statut')),
                ('message', models.TextField(verbose_name='Message')),
                ('valeur_mesure', models.FloatField(blank=True, null=True, verbose_name='Valeur mesurée')),
                ('seuil_franchi', models.FloatField(blank=True, null=True, verbose_name='Seuil franchi')),
                ('date_declenchement', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclenchement')),
                ('date_acquittement', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acquittement")),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('resolution_auto', models.BooleanField(default=False, verbose_name='Résolution automatique')),
                ('acquittee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL, verbose_name='Acquittée par')),
                ('capteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='capteurs.capteur', verbose_name='Capteur')),
                ('mesure_declencheuse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_declenchees', to='capteurs.mesure', verbose_name='Mesure déclencheuse')),
                ('reservoir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='reservoirs.reservoir', verbose_name='Réservoir')),
                ('resolue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_resolues', to=settings.AUTH_USER_MODEL, verbose_name='Résolue par')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_declenchement'],
                'indexes': [models.Index(fields=['statut', '-date_declenchement'], name='alertes_ale_statut_117bb3_idx'), models.Index(fields=['gravite', 'statut'], name='alertes_ale_gravite_ab9de6_idx'), models.Index(fields=['type'], name='alertes_ale_type_c6ea4c_idx'), models.Index(fields=['capteur', 'statut'], name='alertes_ale_capteur_53a363_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'active')), fields=('capteur', 'type'), name='unique_alerte_active_par_capteur_type')],
            },
        ),
    ]
