# Generated by Django 6.1.1 on 2026-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.SlugField(help_text='Identifiant technique (a-z, 0-9, tirets). Utilisé pour les topics MQTT.', unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('localisation', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('capacite_max_litres', models.FloatField(verbose_name='Capacité maximale (L)')),
                ('hauteur_max_cm', models.FloatField(help_text="Utilisé pour convertir la hauteur d'eau (cm) en volume (L).", verbose_name='Hauteur maximale (cm)')),
                ('seuil_critique_bas', models.FloatField(default=10.0, verbose_name='Seuil critique bas (%)')),
                ('seuil_alerte_bas', models.FloatField(default=25.0, verbose_name="Seuil d'alerte bas (%)")),
                ('seuil_alerte_haut', models.FloatField(default=90.0, verbose_name="Seuil d'alerte haut (%)")),
                ('seuil_critique_haut', models.FloatField(default=95.0, verbose_name='Seuil critique haut (%)')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('maintenance', 'En maintenance')], default='actif', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Réservoir',
                'verbose_name_plural': 'Réservoirs',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['statut'], name='reservoirs__statut_28234c_idx'), models.Index(fields=['code'], name='reservoirs__code_10dd27_idx')],
            },
        ),
    ]
